name: flutter_edflib
description: "A wrapper library around EDFLib."
version: 0.1.0
repository: https://github.com/whynot-agency/flutter_edflib

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  version: ^3.0.2

dev_dependencies:
  ffigen: ^15.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
